### PR TITLE
Fix small leaks in conf.c (fixes #184)

### LINKED ISSUE #184: 26 bytes leaked at start-up when reading the config
@jessie-murray do you want to take this as well?

I ran your branch under Valgrind and noticed that there are a few bytes leaked when the config is read (unrelated to your PR). It's really not much (3 allocations for a total of 26 bytes and this only happens once at startup), but it could probably be addressed relatively easily.

Relevant output:
```
==6560== 6 bytes in 1 blocks are definitely lost in loss record 3 of 40
==6560==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==6560==    by 0x4B47DB9: strdup (strdup.c:42)
==6560==    by 0x113406: conf_string_or_envvar (conf.c:53)
==6560==    by 0x113F50: acl_read_commands (conf.c:203)
==6560==    by 0x114306: conf_parse_acl (conf.c:274)
==6560==    by 0x114354: conf_parse_acls (conf.c:289)
==6560==    by 0x1139CA: conf_read (conf.c:135)
==6560==    by 0x10D36E: server_new (server.c:100)
==6560==    by 0x10B6AC: main (webdis.c:11)
==6560==
==6560== 6 bytes in 1 blocks are definitely lost in loss record 4 of 40
==6560==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==6560==    by 0x4B47DB9: strdup (strdup.c:42)
==6560==    by 0x113406: conf_string_or_envvar (conf.c:53)
==6560==    by 0x113F50: acl_read_commands (conf.c:203)
==6560==    by 0x1142C3: conf_parse_acl (conf.c:269)
==6560==    by 0x114354: conf_parse_acls (conf.c:289)
==6560==    by 0x1139CA: conf_read (conf.c:135)
==6560==    by 0x10D36E: server_new (server.c:100)
==6560==    by 0x10B6AC: main (webdis.c:11)
==6560==
==6560== 14 bytes in 1 blocks are definitely lost in loss record 10 of 40
==6560==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==6560==    by 0x4B47DB9: strdup (strdup.c:42)
==6560==    by 0x113406: conf_string_or_envvar (conf.c:53)
==6560==    by 0x114181: conf_parse_acl (conf.c:248)
==6560==    by 0x114354: conf_parse_acls (conf.c:289)
==6560==    by 0x1139CA: conf_read (conf.c:135)
==6560==    by 0x10D36E: server_new (server.c:100)
==6560==    by 0x10B6AC: main (webdis.c:11)

[...]

==6560== LEAK SUMMARY:
==6560==    definitely lost: 26 bytes in 3 blocks
```

### PR DESCRIPTION
**Pull request by jessie-murray**
1. plaintext was not free'd after encoding credentials
2. ACL commands were duplicated when there was no need to

In both cases the value came from conf_string_or_envvar which always
uses strdup.

### CODE REVIEW

File: src/conf.c [hunk 1]
```diff
@@ -252,6 +248,7 @@ conf_parse_acl(json_t *j) {
 
 		base64_init_encodestate(&b64);
 		pos = base64_encode_block(plain, (int)plain_len, a->http_basic_auth, &b64);
+		free(plain);
```
Comment (nicolasff) [inline src/conf.c:251]: Ok, I see the variable declaration you mentioned in the previous PR.

**Review by nicolasff — APPROVED** [review]

**Comment by nicolasff** [comment]
Looks good! Thanks again @jessie-murray.
